// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyhgnqrtirnwaxqemacw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5aGducXJ0aXJud2F4cWVtYWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjM3MjMsImV4cCI6MjA3MTczOTcyM30.jKSZaCQYCl1BfilCR9jrm5l4z4M9BqYxCCQqhO0x4aU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});