// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psfgtshspngjdzkjdnzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZmd0c2hzcG5namR6a2pkbnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDk0NDMsImV4cCI6MjA2OTE4NTQ0M30.xmO1uOyGoYeVdkbHIlQO6tCmwfWWX_ysBj8asKhGato";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});